In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
# Read the csv file into a pandas DataFrame

performance = pd.read_csv('../data/samples.csv')
performance.head()

,otu_id,otu_label,2000,2001,2002,2003,2004,2005,2006,2007,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,1,AXP,0.006869,-0.339676,0.000563,0.359279,0.171095,0.047010,0.185383,-0.143251,...,0.070672,0.106434,0.206819,0.569791,0.034735,-0.243239,0.108990,0.347316,-0.030422,0.304835
1,2,CAT,0.002751,0.163384,-0.099845,0.851785,0.195363,0.224479,0.076721,0.197358,...,0.666731,-0.022303,-0.007904,-0.002906,0.039185,-0.231932,0.444654,0.726567,-0.179165,0.204403
2,3,DIS,0.000113,-0.248466,-0.209897,0.401704,0.205888,-0.128790,0.435979,-0.046332,...,0.175764,0.010597,0.331345,0.522512,0.254216,0.120639,0.025639,0.036984,0.022466,0.346565
3,4,HD,-0.331899,0.120603,-0.526192,0.478752,0.205863,-0.049030,0.012380,-0.330379,...,0.240235,0.229130,0.490326,0.322462,0.306183,0.283122,0.052467,0.435203,-0.076475,0.427053
4,5,IBM,-0.240567,0.438470,-0.352779,0.185081,0.069837,-0.161632,0.194059,0.128171,...,0.140393,0.270309,0.043179,-0.014898,-0.122261,-0.118897,0.270549,-0.045640,-0.230799,0.257397

In [3]:
# Drop columns not needed

performance = performance.drop(['otu_id', 'otu_label'], axis=1)
performance

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,0.006869,-0.339676,0.000563,0.359279,0.171095,0.047010,0.185383,-0.143251,-0.638984,1.258279,0.070672,0.106434,0.206819,0.569791,0.034735,-0.243239,0.108990,0.347316,-0.030422,0.304835
1,0.002751,0.163384,-0.099845,0.851785,0.195363,0.224479,0.076721,0.197358,-0.368758,0.324359,0.666731,-0.022303,-0.007904,-0.002906,0.039185,-0.231932,0.444654,0.726567,-0.179165,0.204403
2,0.000113,-0.248466,-0.209897,0.401704,0.205888,-0.128790,0.435979,-0.046332,-0.286749,0.432804,0.175764,0.010597,0.331345,0.522512,0.254216,0.120639,0.025639,0.036984,0.022466,0.346565
3,-0.331899,0.120603,-0.526192,0.478752,0.205863,-0.049030,0.012380,-0.330379,-0.116666,0.301407,0.240235,0.229130,0.490326,0.322462,0.306183,0.283122,0.052467,0.435203,-0.076475,0.427053
4,-0.240567,0.438470,-0.352779,0.185081,0.069837,-0.161632,0.194059,0.128171,-0.214115,0.591181,0.140393,0.270309,0.043179,-0.014898,-0.122261,-0.118897,0.270549,-0.045640,-0.230799,0.257397
5,-0.277085,0.027439,-0.510107,1.008141,-0.272635,0.069775,-0.179676,0.329087,-0.426530,0.436096,0.042641,0.194452,-0.133559,0.275995,0.452810,-0.032263,0.106119,0.296264,0.037185,0.292457
6,0.141905,0.151746,-0.075660,-0.030887,0.251665,-0.032509,0.106585,0.034375,-0.075747,0.107210,-0.010431,0.085230,0.108091,0.328713,0.179146,0.006958,0.164676,0.237922,-0.050951,0.075296
7,-0.044133,-0.158802,-0.316161,0.503459,0.094612,0.044831,0.251573,-0.069744,-0.254906,0.340350,0.018913,-0.210544,0.329385,0.327490,0.094869,0.076083,0.379889,0.252079,-0.072443,0.392215
8,0.077278,-0.206370,-0.047961,0.172817,-0.161974,-0.012756,0.216498,0.301206,-0.242728,0.298649,0.187011,0.092538,0.062393,0.148889,0.057514,0.050180,0.011214,0.142624,0.067230,0.149156
9,-0.128416,-0.210681,-0.384196,0.558968,0.308512,0.088604,0.323941,0.385053,0.093072,0.036914,0.265408,0.340614,-0.101602,0.120984,0.001155,0.298259,0.070100,0.448566,0.048030,0.125254
10,0.286055,0.021827,0.074855,0.406301,-0.017198,-0.036295,0.026380,0.112934,-0.297260,0.484979,0.065313,-0.033445,0.138405,0.522675,0.219032,-0.061316,0.238501,0.347193,-0.170549,-0.061903
11,0.388044,-0.356181,-0.018401,-0.128434,-0.317250,0.045254,0.395414,0.360145,-0.452670,0.264799,0.020802,0.087838,0.125887,0.240156,0.173469,-0.045951,0.168431,-0.019407,0.392041,0.150402
12,-0.630400,0.501246,-0.224306,0.055847,0.080927,-0.012412,0.153892,0.206282,-0.446852,0.597338,-0.069591,-0.049975,0.034849,0.414239,0.277493,0.221437,0.175239,0.392602,0.199786,0.523683
13,-0.259008,0.035282,0.109682,0.182587,0.126378,0.060791,0.125440,0.167226,-0.135784,0.014134,0.085053,0.069433,0.058312,0.223175,0.155352,-0.097075,0.108383,0.129631,0.035732,0.361397
14,0.274998,-0.158230,-0.028285,0.545048,0.106536,0.101640,0.125629,0.242978,-0.285608,0.335965,0.148325,-0.055277,0.123817,0.394475,0.040476,-0.145576,0.191249,0.182777,-0.149076,0.443615
15,-0.219444,0.089313,-0.119144,0.054353,-0.000555,-0.118553,0.010832,0.028780,0.200502,-0.024381,0.026699,0.132393,0.165613,0.169675,0.118167,-0.269737,0.175712,0.462878,-0.039664,0.317488
16,0.117179,-0.073265,-0.088605,0.204296,0.279813,0.122900,0.384489,0.249603,-0.135611,-0.128529,0.092906,0.177479,0.032476,0.184397,-0.051128,-0.125672,0.205984,-0.045163,-0.152840,0.076716

In [4]:
performance.shape

(17, 20)

In [5]:
performance = (performance.T)
performance.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
2000,0.006869,0.002751,0.000113,-0.331899,-0.240567,-0.277085,0.141905,-0.044133,0.077278,-0.128416,0.286055,0.388044,-0.630400,-0.259008,0.274998,-0.219444,0.117179
2001,-0.339676,0.163384,-0.248466,0.120603,0.438470,0.027439,0.151746,-0.158802,-0.206370,-0.210681,0.021827,-0.356181,0.501246,0.035282,-0.158230,0.089313,-0.073265
2002,0.000563,-0.099845,-0.209897,-0.526192,-0.352779,-0.510107,-0.075660,-0.316161,-0.047961,-0.384196,0.074855,-0.018401,-0.224306,0.109682,-0.028285,-0.119144,-0.088605
2003,0.359279,0.851785,0.401704,0.478752,0.185081,1.008141,-0.030887,0.503459,0.172817,0.558968,0.406301,-0.128434,0.055847,0.182587,0.545048,0.054353,0.204296
2004,0.171095,0.195363,0.205888,0.205863,0.069837,-0.272635,0.251665,0.094612,-0.161974,0.308512,-0.017198,-0.317250,0.080927,0.126378,0.106536,-0.000555,0.279813

In [6]:
performance.shape

(20, 17)

In [7]:
X = performance
print('X ~ n_samples x n_features:', X.shape)

X ~ n_samples x n_features: (20, 17)

In [8]:
# Read the csv file into a pandas DataFrame

potus = pd.read_csv('../data/potus.csv')
potus.head()

   year       potus
0  2000    Democrat
1  2001  Republican
2  2002  Republican
3  2003  Republican
4  2004  Republican

In [9]:
# Reformat data
data = potus.values
y = data[:, 1]
y

array(['Democrat', 'Republican', 'Republican', 'Republican', 'Republican',
       'Republican', 'Republican', 'Republican', 'Republican', 'Democrat',
       'Democrat', 'Democrat', 'Democrat', 'Democrat', 'Democrat',
       'Democrat', 'Democrat', 'Republican', 'Republican', 'Republican'],
      dtype=object)

In [10]:
from sklearn.preprocessing import LabelEncoder

# Label-encode data set
label_encoder = LabelEncoder()
label_encoder.fit(y)
encoded_y = label_encoder.transform(y)

In [11]:
for label, original_class in zip(encoded_y, y):
    print('Original Class: ' + str(original_class))
    print('Encoded Label: ' + str(label))
    print('-' * 12)

Original Class: Democrat
Encoded Label: 0
------------
Original Class: Republican
Encoded Label: 1
------------
Original Class: Republican
Encoded Label: 1
------------
Original Class: Republican
Encoded Label: 1
------------
Original Class: Republican
Encoded Label: 1
------------
Original Class: Republican
Encoded Label: 1
------------
Original Class: Republican
Encoded Label: 1
------------
Original Class: Republican
Encoded Label: 1
------------
Original Class: Republican
Encoded Label: 1
------------
Original Class: Democrat
Encoded Label: 0
------------
Original Class: Democrat
Encoded Label: 0
------------
Original Class: Democrat
Encoded Label: 0
------------
Original Class: Democrat
Encoded Label: 0
------------
Original Class: Democrat
Encoded Label: 0
------------
Original Class: Democrat
Encoded Label: 0
------------
Original Class: Democrat
Encoded Label: 0
------------
Original Class: Democrat
Encoded Label: 0
------------
Original Class: Republican
Encoded Label: 1
------------
Original Class: Republican
Encoded Label: 1
------------
Original Class: Republican
Encoded Label: 1
------------

In [ ]:
from keras.utils import to_categorical

# One-hot encoding
one_hot_y = to_categorical(encoded_y)
one_hot_y

Using TensorFlow backend.

ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "C:\Users\Michael Bell\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2033, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'SystemError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Michael Bell\Anaconda3\lib\site-packages\IPython\core\ultratb.py", line 1095, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "C:\Users\Michael Bell\Anaconda3\lib\site-packages\IPython\core\ultratb.py", line 313, in wrapped
    return f(*args, **kwargs)
  File "C:\Users\Michael Bell\Anaconda3\lib\site-packages\IPython\core\ultratb.py", line 347, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "C:\Users\Michael Bell\Anaconda3\lib\inspect.py", line 1500, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "C:\Users\Michael Bell\Anaconda3\lib\inspect.py", line 1458, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "C:\Users\Michael Bell\Anaconda3\lib\inspect.py", line 696, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "C:\Users\Michael Bell\Anaconda3\lib\inspect.py", line 733, in getmodule
    if ismodule(module) and hasattr(module, '__file__'):
  File "C:\Users\Michael Bell\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\Michael Bell\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\Michael Bell\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tensorflow_core.keras'

Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Users\Michael Bell\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2033, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'SystemError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Michael Bell\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2036, in showtraceback
    value, tb, tb_offset=tb_offset)
  File "C:\Users\Michael Bell\Anaconda3\lib\site-packages\IPython\core\ultratb.py", line 1379, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File "C:\Users\Michael Bell\Anaconda3\lib\site-packages\IPython\core\ultratb.py", line 1282, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File "C:\Users\Michael Bell\Anaconda3\lib\site-packages\IPython\core\ultratb.py", line 1144, in structured_traceback
    formatted_exceptions += self.prepare_chained_exception_message(evalue.__cause__)
TypeError: can only concatenate str (not "list") to str

Original exception was:
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 980, in _find_and_load
SystemError: <class '_frozen_importlib._ModuleLockManager'> returned a result with an error set

ImportError: numpy.core._multiarray_umath failed to import

ImportError: numpy.core.umath failed to import